version: 0.2

env:
  variables:
    ECR_REPO_NAME: api-repository

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_NAME}:latest .
      - echo "Tagging Docker image..."
  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
      - echo "Creating imageDetail.json..."
      - |
        echo '[
          {
            "name": "container-cloudtech-api",
            "imageUri": ${ECR_IMAGE_URI}
          }
        ]' > imageDetail.json
      - echo "imageDetail.json created."
artifacts:
  files:
    - appspec.yml
    - taskdef.json
    - imageDetail.json
  discard-paths: yes
