version: 0.2

env:
  variables:
    ECR_REPOSITORY: 437346259917.dkr.ecr.ap-northeast-1.amazonaws.com/api-repository

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t api-repository .
      - echo "Tagging Docker image..."
      - docker tag api-repository:latest $ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY:latest
      - echo "Build completed on $(date)"
      - echo "Creating imagedefinitions.json..."
      - |
        echo '[
          {
            "name": "container-cloudtech-api",
            "imageUri": "'$ECR_REPOSITORY':latest"
          }
        ]' > imageDetail.json
      - echo "imageDetail.json created."
artifacts:
  files:
    - appspec.yml
    - taskdef.json
    - imageDetail.json
  discard-paths: yes
